import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";
import {Outfit, Urbanist} from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
  weight: "700"
})

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${outfit.variable} ${urbanist.variable} dark`}>
      <body
        className={``}
      >
        <ThemeProvider
            attribute={"class"} enableSystem
          >
              {children}
          </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
